/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wen_app_update_BsPatch */

#ifndef _Included_com_wen_app_update_BsPatch
#define _Included_com_wen_app_update_BsPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wen_app_update_BsPatch
 * Method:    apply
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wen_app_update_BsPatch_apply
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
